version: "3.8"
services:
  app:
    build:
      args:
        user: ${USER_NAME}
        uid: ${UID}
      context: ./
      dockerfile: Dockerfile
    image: dockerlibrary
    container_name: dockerlibrary-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - librarynetwork
  db:
    image: mysql:8.0.28
    container_name: dockerlibrary-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - librarynetwork
  nginx:
    image: nginx:1.19.10-alpine
    container_name: dockerlibrary-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - librarynetwork
networks:
  librarynetwork:
    driver: bridge
